namespace NodeJS {
  interface ProcessEnv {
    

    NEXT_PUBLIC_EXTERNAL_API_URL: string;
    NEXT_PUBLIC_MEALS_API_URL: string;
    NEXT_PUBLIC_CHAT_API_URL: string;
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: string;
    NEXT_PUBLIC_APP_URL: string;
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: string;
    CLERK_SECRET_KEY: string;
    NEXT_PUBLIC_CLERK_SIGN_IN_URL: string;
    NEXT_PUBLIC_CLERK_SIGN_UP_URL: string;
    SYSTEM_USER_EMAIL: string;
    SYSTEM_USER_PASSWORD: string;
    NEXT_PUBLIC_POSTHOG_KEY: string;
    NEXT_PUBLIC_POSTHOG_HOST: string;
    NEXT_PUBLIC_APP_ENV: string;
    NEXT_PUBLIC_CHAT_WS_URL: string;
    NEXT_PUBLIC_BROWSER_API_KEY: string;
  }
}