"use server";

import { axiosAWSInstance } from "@/axios";
import { IMoviesPayload, List } from "@/types";
import { auth } from "@clerk/nextjs/server";
import validator from "validator";

export const fetchLists = async () => {
  // Get token
  const { getToken } = await auth();
  const token = await getToken();

  // Get user's list
  const { data: lists } = await axiosAWSInstance({
    method: "get",
    url: process.env.AWS_API_GATEWAY_URL,
    headers: {
      "Authorization": `Bearer ${token}`,
      "Content-Type": "application/json"
    }
  });

  return lists;
}

export const fetchListById = async (listId: List["listId"]) => {
  // Make sure list ID is a valid uuid v4
  if (!listId || !validator.isUUID(listId, 4))
    throw new AppError("Invalid list id", 400);

  // Get list data from DB
  const { getToken } = await auth();
  const token = await getToken();
  const { data: list } = await axiosAWSInstance({
    method: "get",
    url: `${process.env.AWS_API_GATEWAY_URL}/${listId}`,
    headers: {
      Authorization: `Bearer ${token}`
    }
  });

  return list;
}

export const fetchMoviesByCategory = async ({category, page}: IMoviesPayload) => {
  return { results: mockMovies };
}

const mockMovies = [
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [],
    id: 1,
    original_language: "",
    original_title: "Movie 1",
    overview: "",
    popularity: 0,
    poster_path: "",
    release_date: "",
    title: "Movie 1",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [],
    id: 2,
    original_language: "",
    original_title: "Movie 2",
    overview: "",
    popularity: 0,
    poster_path: "",
    release_date: "",
    title: "Movie 2",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [],
    id: 3,
    original_language: "",
    original_title: "Movie 3",
    overview: "",
    popularity: 0,
    poster_path: "",
    release_date: "",
    title: "Movie 3",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [],
    id: 4,
    original_language: "",
    original_title: "Movie 4",
    overview: "",
    popularity: 0,
    poster_path: "",
    release_date: "",
    title: "Movie 4",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [],
    id: 5,
    original_language: "",
    original_title: "Movie 5",
    overview: "",
    popularity: 0,
    poster_path: "",
    release_date: "",
    title: "Movie 5",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [],
    id: 1,
    original_language: "",
    original_title: "Movie 1",
    overview: "",
    popularity: 0,
    poster_path: "",
    release_date: "",
    title: "Movie 1",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [],
    id: 2,
    original_language: "",
    original_title: "Movie 2",
    overview: "",
    popularity: 0,
    poster_path: "",
    release_date: "",
    title: "Movie 2",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [],
    id: 3,
    original_language: "",
    original_title: "Movie 3",
    overview: "",
    popularity: 0,
    poster_path: "",
    release_date: "",
    title: "Movie 3",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [],
    id: 4,
    original_language: "",
    original_title: "Movie 4",
    overview: "",
    popularity: 0,
    poster_path: "",
    release_date: "",
    title: "Movie 4",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [],
    id: 5,
    original_language: "",
    original_title: "Movie 5",
    overview: "",
    popularity: 0,
    poster_path: "",
    release_date: "",
    title: "Movie 5",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [],
    id: 1,
    original_language: "",
    original_title: "Movie 1",
    overview: "",
    popularity: 0,
    poster_path: "",
    release_date: "",
    title: "Movie 1",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [],
    id: 2,
    original_language: "",
    original_title: "Movie 2",
    overview: "",
    popularity: 0,
    poster_path: "",
    release_date: "",
    title: "Movie 2",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [],
    id: 3,
    original_language: "",
    original_title: "Movie 3",
    overview: "",
    popularity: 0,
    poster_path: "",
    release_date: "",
    title: "Movie 3",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [],
    id: 4,
    original_language: "",
    original_title: "Movie 4",
    overview: "",
    popularity: 0,
    poster_path: "",
    release_date: "",
    title: "Movie 4",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [],
    id: 5,
    original_language: "",
    original_title: "Movie 5",
    overview: "",
    popularity: 0,
    poster_path: "",
    release_date: "",
    title: "Movie 5",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [],
    id: 1,
    original_language: "",
    original_title: "Movie 1",
    overview: "",
    popularity: 0,
    poster_path: "",
    release_date: "",
    title: "Movie 1",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [],
    id: 2,
    original_language: "",
    original_title: "Movie 2",
    overview: "",
    popularity: 0,
    poster_path: "",
    release_date: "",
    title: "Movie 2",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [],
    id: 3,
    original_language: "",
    original_title: "Movie 3",
    overview: "",
    popularity: 0,
    poster_path: "",
    release_date: "",
    title: "Movie 3",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [],
    id: 4,
    original_language: "",
    original_title: "Movie 4",
    overview: "",
    popularity: 0,
    poster_path: "",
    release_date: "",
    title: "Movie 4",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [],
    id: 5,
    original_language: "",
    original_title: "Movie 5",
    overview: "",
    popularity: 0,
    poster_path: "",
    release_date: "",
    title: "Movie 5",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
];