import { List } from "@/types";

export const mockList = {
  listId: "4",
  listName: "Sci-Fi Classics",
  movies: [
    { id: "1", name: "Inception" },
    { id: "2", name: "The Matrix" },
    { id: "3", name: "Interstellar" },
    { id: "4", name: "Blade Runner" },
    { id: "5", name: "The Prestige" }
  ],
  createdAt: new Date("2024-04-25").toISOString(),
  updatedAt: new Date("2024-04-25").toISOString()
}

export const mockLists: List[] = [
  {
    listId: "1",
    listName: "Action Favorites",
    movies: [],
    createdAt: new Date("2024-01-10").toISOString(),
    updatedAt: new Date("2024-01-10").toISOString(),
  },
  {
    listId: "2",
    listName: "Comedy Nights",
    movies: [],
    createdAt: new Date("2024-02-15").toISOString(),
    updatedAt: new Date("2024-02-15").toISOString(),
  },
  {
    listId: "3",
    listName: "Drama Picks",
    movies: [],
    createdAt: new Date("2024-03-20").toISOString(),
    updatedAt: new Date("2024-03-20").toISOString(),
  },
  {
    listId: "4",
    listName: "Sci-Fi Classics",
    movies: [],
    createdAt: new Date("2024-04-25").toISOString(),
    updatedAt: new Date("2024-04-25").toISOString(),
  },
];

export const mockMovies = [
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [],
    id: 1,
    original_language: "",
    original_title: "Movie 1",
    overview: "This is a really long overview!",
    popularity: 0,
    poster_path: "",
    release_date: "",
    title: "Movie 1",
    video: false,
    vote_average: 7.5,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [],
    id: 2,
    original_language: "",
    original_title: "Movie 2",
    overview: "",
    popularity: 0,
    poster_path: "",
    release_date: "",
    title: "Movie 2",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [],
    id: 3,
    original_language: "",
    original_title: "Movie 3",
    overview: "",
    popularity: 0,
    poster_path: "",
    release_date: "",
    title: "Movie 3",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [],
    id: 4,
    original_language: "",
    original_title: "Movie 4",
    overview: "",
    popularity: 0,
    poster_path: "",
    release_date: "",
    title: "Movie 4",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [],
    id: 5,
    original_language: "",
    original_title: "Movie 5",
    overview: "",
    popularity: 0,
    poster_path: "",
    release_date: "",
    title: "Movie 5",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [],
    id: 6,
    original_language: "",
    original_title: "Movie 6",
    overview: "",
    popularity: 0,
    poster_path: "",
    release_date: "",
    title: "Movie 6",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [],
    id: 7,
    original_language: "",
    original_title: "Movie 7",
    overview: "",
    popularity: 0,
    poster_path: "",
    release_date: "",
    title: "Movie 7",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [],
    id: 8,
    original_language: "",
    original_title: "Movie 8",
    overview: "",
    popularity: 0,
    poster_path: "",
    release_date: "",
    title: "Movie 8",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [],
    id: 9,
    original_language: "",
    original_title: "Movie 9",
    overview: "",
    popularity: 0,
    poster_path: "",
    release_date: "",
    title: "Movie 9",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [],
    id: 10,
    original_language: "",
    original_title: "Movie 10",
    overview: "",
    popularity: 0,
    poster_path: "",
    release_date: "",
    title: "Movie 10",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [],
    id: 11,
    original_language: "",
    original_title: "Movie 11",
    overview: "",
    popularity: 0,
    poster_path: "",
    release_date: "",
    title: "Movie 1",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [],
    id: 12,
    original_language: "",
    original_title: "Movie 12",
    overview: "",
    popularity: 0,
    poster_path: "",
    release_date: "",
    title: "Movie 2",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [],
    id: 13,
    original_language: "",
    original_title: "Movie 13",
    overview: "",
    popularity: 0,
    poster_path: "",
    release_date: "",
    title: "Movie 3",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [],
    id: 14,
    original_language: "",
    original_title: "Movie 14",
    overview: "",
    popularity: 0,
    poster_path: "",
    release_date: "",
    title: "Movie 4",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [],
    id: 15,
    original_language: "",
    original_title: "Movie 15",
    overview: "",
    popularity: 0,
    poster_path: "",
    release_date: "",
    title: "Movie 15",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [],
    id: 16,
    original_language: "",
    original_title: "Movie 16",
    overview: "",
    popularity: 0,
    poster_path: "",
    release_date: "",
    title: "Movie 16",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [],
    id: 17,
    original_language: "",
    original_title: "Movie 17",
    overview: "",
    popularity: 0,
    poster_path: "",
    release_date: "",
    title: "Movie 17",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [],
    id: 18,
    original_language: "",
    original_title: "Movie 18",
    overview: "",
    popularity: 0,
    poster_path: "",
    release_date: "",
    title: "Movie 18",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [],
    id: 19,
    original_language: "",
    original_title: "Movie 19",
    overview: "",
    popularity: 0,
    poster_path: "",
    release_date: "",
    title: "Movie 19",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [],
    id: 20,
    original_language: "",
    original_title: "Movie 20",
    overview: "",
    popularity: 0,
    poster_path: "",
    release_date: "",
    title: "Movie 20",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
];